server:
  port: ${PORT:${SERVERS_PORT:8080}}

logging:
  level:
    root: info
    org.springframework.cloud.gateway: debug
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: info

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8090/eureka}
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedHeaders: "*"
            allowedMethods: "GET,POST,PUT,DELETE,OPTIONS"
      discovery:
        locator:
          enable: true
      routes:
        - id: ms-auth-service
          uri: lb://ms-auth-service
          predicates:
            - Path=/auth/**

        - id: ms-cliente-service
          uri: lb://ms-cliente-service
          predicates:
            - Path=/api/clientes/**


        - id: ms-categoria-service
          uri: lb://ms-categoria-service
          predicates:
            - Path=/api/categorias/**


        - id: ms-proveedor-service
          uri: lb://ms-proveedor-service
          predicates:
            - Path=/api/proveedores/**

        - id: ms-compra-service
          uri: lb://ms-compra-service
          predicates:
            - Path=/api/compras/**

        - id: ms-inventario-service
          uri: lb://ms-inventario-service
          predicates:
            - Path=/api/stock/**

        - id: ms-producto-service
          uri: lb://ms-producto-service
          predicates:
            - Path=/api/productos/**

        - id: ms-venta-service
          uri: lb://ms-venta-service
          predicates:
            - Path=/api/ventas/**
