server:
  port: ${PORT:${SERVER_PORT:8086}}

spring:
  application:
    name: ms-inventario-service

  datasource:
    url: jdbc:h2:mem:inventariodb
    driver-class-name: org.h2.Driver
    username: sa
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true
      path: /h2-console

# Feign: URL base para ms_producto
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
  producto:
    url: http://localhost:8083/api/productos

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8090/eureka}
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}