server:
  port: ${PORT:${SERVER_PORT:8082}}

spring:
  application:
    name: ms-proveedor-service
  cloud:
    discovery:
      enabled: true

eureka:
  client:
    serviceUrl:

      defaultZone: ${EUREKA_URI:http://localhost:8090/eureka}
  instance:
    #hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

  datasource:
    url: jdbc:h2:mem:ms_proveedores
    driver-class-name: org.h2.Driver
    username: sa
    password: password
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
    h2:
      console:
        enabled: true
        path: /h2-console

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /doc/swagger-ui.html

feign:
  sunat:
    base-url: https://api.apis.net.pe/v1
